version: '3.8'

services:
  diyawannasupbackend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      # Ensure these match your appsettings.json keys
      - MongoDbSettings__ConnectionString=mongodb+srv://<username>:<password>@<cluster>.mongodb.net/diyawanna_sup_main?retryWrites=true&w=majority
      - MongoDbSettings__DatabaseName=diyawanna_sup_main
      - JwtSettings__Secret=your-production-secret-key-256-bits-or-longer
      - JwtSettings__ExpirationMinutes=60
    # Optional: Link to a MongoDB container if running locally
    # depends_on:
    #   - mongodb
    # networks:
    #   - app-network

  # Optional: Local MongoDB container
  # mongodb:
  #   image: mongo:7.0
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   mongodb_data:
